// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1P7Nv1C3s7NqKUlwDb4liam1Yclp5G1I',
    appId: '1:649908007970:web:56626de6fb30e360d6067b',
    messagingSenderId: '649908007970',
    projectId: 'ecoera-fourfront',
    authDomain: 'ecoera-fourfront.firebaseapp.com',
    storageBucket: 'ecoera-fourfront.appspot.com',
    measurementId: 'G-4WKT9DBD62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHRkjsVA6BP_XfiEgZFsueA-CZULQNljs',
    appId: '1:649908007970:android:aad429c9c0567cc5d6067b',
    messagingSenderId: '649908007970',
    projectId: 'ecoera-fourfront',
    storageBucket: 'ecoera-fourfront.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWXT_yqCzTAE7fbAZwbH5Uc8HCVSQ5Xik',
    appId: '1:649908007970:ios:9c3e239df246205bd6067b',
    messagingSenderId: '649908007970',
    projectId: 'ecoera-fourfront',
    storageBucket: 'ecoera-fourfront.appspot.com',
    iosClientId: '649908007970-3p5bivsndrvhs3k9obtpu2ofcs6ldmla.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoera',
  );
}
